### ISSUE TITLE
Review lab1

### ISSUE THREAD

**Issue by jovfer** [katerina-klimova/for_labs#1]
https://github.com/katerina-klimova/for_labs/blob/c057d6dc10b7862d836818fe80f4681eeac5e1cf/Sources/ConsoleApplication_laba_1_c%2B%2B(2)/ConsoleApplication_laba_1_c%2B%2B(2).cpp#L57-58
В этих двух строках сразу три ошибки:
1) "утекает" память
2) неправильно перессчитывается итоговый размер
3) неправильно переприсваиваивается строка

Подсказка для исправления логических ошибок - следующий тест:
4  7  8  6  4  
6  7  3  10  2  
3  8  1  10  4  
7  1  7  3  7  
2  9  8  10  3

**Comment by jovfer** [comment]
https://github.com/katerina-klimova/for_labs/blob/c057d6dc10b7862d836818fe80f4681eeac5e1cf/Sources/ConsoleApplication_laba_1_c%2B%2B(2)/ConsoleApplication_laba_1_c%2B%2B(2).cpp#L38
тут мне непонятна вторая часть условия:
во-первых, зачем-то перед ним стоит бинарная опирация "и" `&` (Опечатка, имелось ввиду логическое "и"  `&&`?)
во-вторых, при такой организации циклов это условие всегда истино

**Comment by jovfer** [comment]
Ну и в методе распечатки матрицы не хватает переноса между строчками

**Comment by katerina-klimova** [comment]
Кажется получилось исправить

**Comment by jovfer** [comment]
@katerina-klimova Осталась утечка памяти: когда идет присваивание указателя одной строки на место старой, указатель на старую пропадает и не очищается при финальном вызове `delete[]`

**Comment by katerina-klimova** [comment]
Теперь эти строки очищаются отдельно

**Comment by jovfer** [comment]
@katerina-klimova стало чуть ближе к правде. `delete[]` удалит только массив верхнего уровня. Т.е. ту память, которая была выделана на 95 строке. Но нужно освободить еще и всю память, которая выделялась на 98

**Comment by katerina-klimova** [comment]
@jovfer А так?

**Comment by jovfer** [comment]
@katerina-klimova 
1) "нужные" строки все равно дожили до конца и память под них утекла после `delete[] Arr`
2) вызывать `delete[]` после присваивания указателю `null` уже поздно

**Comment by katerina-klimova** [comment]
@jovfer теперь вызываю delete[] без присваивания указателю null, срабатывает до конца, но последнюю строку печатает неверно, точнее уже из "кучи"

**Comment by jovfer** [comment]
@katerina-klimova на самом деле нужно и delete и nullptr. Только изначально неправильный порядок был.

И по-прежнему остаются стоки в памяти, которые ответ. При освобождении двумерного массива заведенного текущим способом, надо сначала вызвать free для всех вложенных и только потом для верхнего уровня.
